### PR TITLE
Create Telegram GitHub Notifier

### PR DESCRIPTION
**Pull request by aaronsms**
Add an automated Telegram notifier whenever a push or pull request is made. A workflow file is added to run with the secrets specified in GitHub repository settings.

### CODE REVIEW

**Comment by aaronsms** [comment]
@daniellau88 it's your call, the workflow build fails because it tries to access the secrets from the master repository. Other than the access issues, it should be working.

**Comment by daniellau88** [comment]
Hi, you can check out the branch `telegram-github-notifier` on the master repository. It seems that the build isn't working there as well.

```
Forbidden: bot can't send messages to bots
```

**Comment by aaronsms** [comment]
Yeap seems like I have included the wrong token. I have updated the secret with the chat ID of our Telegram group.

**Comment by aaronsms** [comment]
Now the issue is the workflow works for push events, but not from the pr from forked, because GitHub doesn't expose secrets to forked-triggered workflows. Seems like we have to close this one down, as our current workflow, we are not pushing/pr-ing from master repository's branches, the notifier doesn't work in this case.

**Comment by aaronsms** [comment]
Since this will not work for our current workflow, unless using plain text tokens, I will close this down. Maybe use it for v1.3.

**Comment by aaronsms** [comment]
Since this will not work for our current workflow, unless using plain text tokens, I will close this down. Maybe use it for v1.3.

**Pull request closed without merging**
